kind: pipeline
name: default

steps:
- name: build image  
  image: plugins/docker
  settings:
    repo: nwd.me/pda
    tags:
      - ${DRONE_BRANCH}
      - latest
    registry: nwd.me
    username: drone
    password: { from_secret: docker_password }
